-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'








-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    input = {
        kb_layout = "es",
        accel_profile = "flat",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = -0.3,
    },
})

hl.config({
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgb(ff79c6)", "rgb(8BE9FD)" }, angle = 315 },
            inactive_border = "rgba(6272a4aa)",
        },
    },
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
    },
})

hl.config({
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 10,
        blur = {
            enabled = true,
            size = 7,
            passes = 4,
            new_optimizations = true,
        },
        shadow = {
            enabled = true,
            color = "rgba(1E202966)",
            range = 60,
            offset = "1 2",
            render_power = 3,
            scale = .97,
        },
    },
})

hl.config({
    animations = {
        enabled = true,
        -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})

hl.config({
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        preserve_split = true,
        -- you probably want this
    },
})

hl.config({
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        new_status = "master",
    },
})

hl.window_rule({
    name  = "opacity_0_8_0_8",
    match = {
        class = "kitty",
    },
    opacity = "0.8 0.8",
})

hl.window_rule({
    animation = "popin",
    match = {
        class = "kitty",
    },
    -- TODO: review rule: "animation popin"
})

hl.window_rule({
    animation = "popin",
    match = {
        class = "thunar",
    },
    -- TODO: review rule: "animation popin"
})

hl.window_rule({
    name  = "opacity_0_8_0_8",
    match = {
        class = "thunar",
    },
    opacity = "0.8 0.8",
})

hl.window_rule({
    name  = "move_cursor_-3__-105",
    match = {
        class = "wofi",
    },
    move = "cursor -3% -105%",
})

hl.window_rule({
    name  = "no_anim",
    match = {
        class = "wofi",
    },
    -- TODO: review rule: "no_anim on"
})

hl.window_rule({
    name  = "opacity_0_8_0_6",
    match = {
        class = "wofi",
    },
    opacity = "0.8 0.6",
})


local bindings = require("bindings")


local media_binds = require("media-binds")



local env_var = require("env_var")



local env_var_nvidia = require("env_var_nvidia")


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("~/.config/scripts/random_wallpaper.sh")
    hl.exec_cmd("waybar -c ~/.config/wayba")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("systemctl --user restart xdg-desktop-portal-hyprland")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("~/.config/scripts/random_wallpaper.sh")
    hl.exec_cmd("waybar -c ~/.config/waybar/config.jsonc & -s ~/.config/waybar/style.css")
    hl.exec_cmd("mako")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("hyprctl setcursor Dracula-cursors 24")
    hl.exec_cmd("~/.config/scripts/set-displays.sh")
end)

hl.monitor({
	output   = "DP-2",
	mode     = "2560x1440@144.00Hz",
	position = "auto",
	scale    = 1,
})
